version: "3.8"

services:
  web:
    build:
      context: .
      network: host
    volumes:
      - "./html:/var/lib/nginx/html"
    networks:
      - docker_default
      - default
    environment:
      - DB_HOST=db
      - DB_DATABASE=web
      - DB_USERNAME=root
      - DB_PASSWORD=web
      - REDIS_HOST=redis
    labels:
      - "traefik.http.routers.web.rule=Host(`web.localhost`)"
  db:
    image: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=web
      - MARIADB_DATABASE=web
  redis:
    image: redis
  
networks:
  docker_default:
    external: true
    name: docker_default
